### ISSUE TITLE
dead links in emacs-tutor part 1

### ISSUE THREAD

**Issue by rahiel** [tuhdo/tuhdo.github.io#30]
The very last link ```Lisp Machine online museum``` and the link ```Why I Still Use Emacs``` from the section ```Other people’s “Why Emacs?”``` are both dead.

**Comment by tuhdo** [comment]
Thanks for reporting. It's a pity. The first link was really good. It contains A LOT of screenshots.

The second link is redundant with another the link in the guide, so it's ok to remove.
