### ISSUE TITLE
volatile-highlights  doesn't exit ?

### ISSUE THREAD

**Issue by minotaur-0** [tuhdo/tuhdo.github.io#34]
Hi 
First, I want to thank you for you very good tutorial.
And I want to ask about the package "volatile-highlights" mentioned in URL below. it seems that it doesn't exit in melpa  anymore.
http://tuhdo.github.io/emacs-tutor3.html

**Comment by tuhdo** [comment]
Hi,

`volatile-highlights` still exists. You can check it [here](http://melpa.org/#/volatile-highlights).

Are you sure you added MELPA already?

And glad that you like my guides!

**Comment by minotaur-0** [comment]
I used 
```emacs-lisp
(require 'package)
(add-to-list 'package-archives 
	'("melpa" . "http://melpa.milkbox.net/packages/") t)
```
and that's what I found http://paste.debian.net/287837/

**Comment by tuhdo** [comment]
All those packages are from ELPA, not MELPA. Packages from MELPA use the date of the latest commits as it version number i.e. `20150731`.

You should paste this code from MELPA [Getting Started](http://melpa.org/#/getting-started) page:

```elisp
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line
```

and paste it in `~/.emacs.d/init.el`.

**Comment by minotaur-0** [comment]
So, this doesn't work anymore ?
```emacs-lisp
(require 'package)
(add-to-list 'package-archives 
	'("melpa" . "http://melpa.milkbox.net/packages/") t)
```

**Comment by hhnr** [comment]
@minotaur-0 I have the same code as you posted. *volatile-highlights* package lists in my *package-list-packages* command. Can you try calling *package-refresh-contents* and check once again?

**Comment by minotaur-0** [comment]
@hhnr 
the code posted by tuhdo works well :)
```emacs-lisp
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line
```
